apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090/prometheus
    isDefault: true
    jsonData:
      httpMethod: "POST"
    editable: false
    version: 1
remote_write:
      - url: https://prometheus-prod-37-prod-ap-southeast-1.grafana.net/api/prom/push
        basic_auth:
          username: 1269663
          password: glc_eyJvIjoiOTgxODU4IiwibiI6InN0YWNrLTc4MDg4MS1pbnRlZ3JhdGlvbi1tYndjbG91ZCIsImsiOiJJbHNDOW1ZMDg5MzlENTkxbUlRT1dYNFMiLCJtIjp7InIiOiJwcm9kLWFwLXNvdXRoZWFzdC0xIn19
